package dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import model.RevenueItem;

public class SalesDao {

    public List<RevenueItem> getSalesReport(String month, String year) {
        List<RevenueItem> revenueItems= new ArrayList<RevenueItem>();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            String query="SELECT * from Orders where MONTH(Orders.Time)=? and YEAR(Orders.Time)=?;\n";
        Connection con = DriverManager.getConnection("jdbc:mysql://mysql4.cs.stonybrook.edu:3306/zhaowhuang", "zhaowhuang", "111067886");
        PreparedStatement ps = con.prepareStatement(query);

        ps.setInt(1,Integer.parseInt(month));
        ps.setInt(2,Integer.parseInt(year));
        ResultSet rs=ps.executeQuery();
            while (rs.next()){

                RevenueItem item= new RevenueItem();
                item.setAccountId(rs.getString("ClientID"));
                item.setAmount(rs.getInt("PricePerShare")*rs.getInt("NumberOfShare"));
                item.setDate(rs.getDate("Time"));
                item.setPricePerShare(rs.getDouble("PricePerShare"));
                item.setStockSymbol(rs.getString("StockSymbol"));
                item.setNumShares(rs.getInt("NumberOfShare"));
                revenueItems.add(item);
            }
        System.out.println(month+year);}
        catch (Exception e){
            e.printStackTrace();
        }
		/*
		 * The students code to fetch data from the database will be written here
		 * Query to get sales report for a particular month and year
		 */

        return revenueItems;

    }



    public List<RevenueItem> getSummaryListing(String searchKeyword) {

		/*
		 * The students code to fetch data from the database will be written here
		 * Query to fetch details of summary listing of revenue generated by a particular stock,
		 * stock type or customer must be implemented
		 * Store the revenue generated by an item in the amount attribute
		 */
        List<RevenueItem> revenueItems= new ArrayList<RevenueItem>();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            ArrayList<String> orderID=new ArrayList<String>();
            String query="SELECT Orders.* from Orders,Stock,Person where (CompanyName like ? and Orders.StockSymbol=Stock.StockSymbol) or ((Person.FirstName like ? or Person.LastName like ? )and Orders.ClientID=Person.SSN) or ((Stock.StockType like ? and Orders.StockSymbol=Stock.StockSymbol));\n";
            Connection con = DriverManager.getConnection("jdbc:mysql://mysql4.cs.stonybrook.edu:3306/zhaowhuang", "zhaowhuang", "111067886");
            searchKeyword="'%"+searchKeyword+"%'";
            query=query.replace("?",searchKeyword);
            System.out.println();
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet rs=ps.executeQuery();
            while (rs.next()){
                RevenueItem item= new RevenueItem();
                item.setAccountId(rs.getString("ClientID"));
                item.setAmount(rs.getInt("PricePerShare")*rs.getInt("NumberOfShare"));
                item.setDate(rs.getDate("Time"));
                item.setPricePerShare(rs.getDouble("PricePerShare"));
                item.setStockSymbol(rs.getString("StockSymbol"));
                item.setNumShares(rs.getInt("NumberOfShare"));
                revenueItems.add(item);
            }

        }
        catch (Exception e){
            e.printStackTrace();
        }
        /*
         * The students code to fetch data from the database will be written here
         * Query to get sales report for a particular month and year
         */

        return revenueItems;
    }
}
